config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  resources :menus, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user

  validates :recommend_title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 255 }

  #TODO: 複数条件の指定、order以外を指定する場合などに問題が発生する可能性ある
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :menus, dependent: :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                              BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all.page(params[:page]).per(15)
  end

  def new
    @menus = Menu.new
  end

  def create
    @menu = Menu.create(menu_params)
    @menu.user = current_user
    if @menu.save
      flash[:success] = '投稿が完了しました'
      redirect_to menus_path
    else
      flash[:danger] = '投稿が失敗しました'
      redirect_to new_menu_path
    end
  end

  def show

  end

  private

  def menu_params
    params.require(:menu).permit(:name, :recommend_title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_to @user, alert: "ログインしました。"
    else
      flash.now[:danger] = "EmailとPasswordの組み合わせに誤りがあります"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url, alert: "ログアウトしました。"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "登録完了しました"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%# TODO: コピーライトの年が手動更新のため、自動更新にする %>
  <small>
    &copy; 2020 Yutaka Yamaki
  </small>
  <nav>
    <ul>
      <li><%= link_to "about me",   about_path %></li>
      <li><%= link_to "contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">news</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Rekomen App", root_path, id: "logo", style: "text-transform: lowercase; font-family: 'Trebuchet MS', sans-serif;" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "投稿一覧", menus_path, style: 'color: #fff;' %></li>
          <li><%= link_to "マイページ", current_user, style: 'color: #fff;' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
         <li><%= link_to "新規登録", signup_path, style: 'color: #fff' %></li>
          <li><%= link_to "ログイン", login_path, style: 'color: #fff' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag     'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag     'https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/css/swiper.min.css' %>
<%= javascript_include_tag  'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default'%>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class:"alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/menus/create.html.erb
<h1>Menus#create</h1>
<p>Find me in app/views/menus/create.html.erb</p>

app/views/menus/index.html.erb
<div class= "d-flex align-items-center">
  <h1>みんなのおすすめ！</h1>
</div>

<div class= "ml-auto buttom">
    <a class= "btn btn-outline-info" href= "/menus/new" role="button">オススメを投稿する</a>
</div>

<table class= "table border-primary">
  <thead>
    <tr>
      <th scope= "col">メニュー名</th>
      <th scope= "col">こんな時におすすめ</th>
      <th scope= "col">おすすめ一言</th>
      <th scope= "col">投稿者</th>
      <th scope= "col">投稿日</th>
    </tr>
  </thead>
  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.recommend_title %></td>
        <td><%= menu.description %></td>
        <td><%= menu.user.name %></td>
        <td><%= menu.created_at.strftime('%Y/%m/%d %H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @menus %>

app/views/menus/new.html.erb
<div class="d-flex align-items-center">
  <h1>投稿</h1>
  <div class="ml-auto posts_button">
      <a class="btn btn-outline-info" href="/menus">投稿一覧</a>
  </div>
</div>

<%= form_for @menus do |f| %>
  <div class="form-group">
      <%= f.label :name, 'メニュー名' %>
      <%= f.text_field :name, class: 'form-control' %>
      <small id="poster-tip" class="form-text text-muted">
          あなたの名前を入力してください。
      </small>
  </div>
  <div class="form-group">
      <%= f.label :recommend_title, 'こんな時にオススメ！' %>
      <%= f.text_field :recommend_title, class: 'form-control' %>
      <small id="title-tip" class="form-text text-muted">
          タイトルを入力してください。
      </small>
  </div>
  <div class="form-group">
      <%= f.label :description, 'おすすめ内容' %>
      <%= f.text_area :description, class: 'form-control', rows:10 %>
      <small id="content-tip" class="form-text text-muted">
          投稿内容を入力してください。
      </small>
  </div>
  <%= f.submit 'オススメを投稿する', class: 'btn btn-info btn-block' %>
  <small id="submit-tip" class="form-text text-muted">
      投稿する前に投稿内容を見直してください!
  </small>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id ="error_explantion" %>
    <div class ="alert alert-danger" %>
      <%= pluralize(@user.errors.count, "error") %>があります。 <%# pluralizaメソッドでエラーの数に応じて活用された単語を返す%>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
    <% end %>
    </ul>
  </div>
<%end%>

app/views/static_pages/about.html.erb
<% provide(:title,"about") %>
<h1>About</h1>
    <p>
      <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
      is a <a href="https://railstutorial.jp/#ebook">book</a> and
      <a href="https://railstutorial.jp/#screencast">screencast</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,"help") %>
<h1>Help</h1>
    <p>  Get help on the Ruby on Rails Tutorial at the
    <a href="https://railstutorial.jp/help">Rails Tutorial helppage</a>.
    To get help on this sample app, see the
    <a href="https://railstutorial.jp/#ebook">
    <em>Ruby on Rails Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="head-container">
  <%= image_tag 'toppage.jpg' %>
    <p>rekomen app</p>
</div>

<div class="heading-container">
  <h2>こんなことでお悩みはないですか？</h2>

<div class="main-container">
  <div class="main-img">
    <div class = "main-item"><%= image_tag 'diet.jpg', size: '320x240' %>
      <p>野菜中心の<br>ダイエットweekにしたい！</p>
    </div>
    <div class = "main-item"><%= image_tag 'sports.jpg', size: '320x240' %>
      <p>タンパク質中心の<br>体引き締めweekしたい！</p>
    </div>
    <div class = "main-item"><%= image_tag 'meal_with_friends.jpg', size: '320x240' %>
      <p>オシャレで映える<br>食事weekにしたい！</p>
    </div>
  </div>
</div>

<div class="desc-container">
  <p>
    今週はこんなシーンに合わせたWeek Menuにしたい♪
    <br>
    <br>
    でも張り切って妄想したのも束の間、
    <br>
    1週間の献立作りがめんどくさい。。1週間も何作ればいいの。。今月はどんなメニュー作ったっけ。。
    <br>
    実際はこんな現実が待ち受けております。
    <br>
    <br>
    そんな現実に打ち勝ち、理想的な1週間を過ごすために、
    <br>
    みなさんの体験とアイデアから、あなたの理想のシーンに合わせて
    <br>
    Week Menuをレコメンドします！
  </p>
</div>

<div class="detail-container">
  <div class="summary-container">
    <h1>
      &#10004 rekomen appを使って
      <br>
      あなた好みのWeek Menuを作ろう！
      <br>
      <br>
    </h1>
    <p>
      使い方は簡単！登録後、あなた好みのシーンを選択するだけ！
      <br>
      あなたの体験とアイデアが、みなさんの素敵な1週間を作ります。
      <br>
      理想のWeek Menuを作り、素敵な1週間を過ごしましょう！
    </p>
  </div>
  <span class="action-container">
     <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary btn-login" %>
     <br>
     <%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary btn-signup" %>
  </span>
</div>

<div class="btn-sns">
  <ul class="snsbtniti">
    <li><a href="https://twitter.com/hachimaki37" class="flowbtn fl_tw"><i class="fab fa-twitter"></i><div>Twitter</div></a></li>
    <li><a href="https://www.sejuku.net/blog/105961" class="flowbtn insta_btn"><i class="fab fa-instagram"></i><div>Instagram</div></a></li>
    <li><a href="https://www.sejuku.net/blog/105961" class="flowbtn fl_fb"><i class="fab fa-facebook-f"></i><div>Facebook</div></a></li>
    <li><a href="https://www.sejuku.net/blog/105961" class="flowbtn fl_hb"><i class="fas fa-bold"></i><div>Hatena</div></a></li>
    <li><a href="https://www.sejuku.net/blog/105961" class="flowbtn fl_ma"><i class="far fa-envelope"></i><div>Contact</div></a></li>
  </ul>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sigh up') %>
<h1>新規登録画面</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, placeholder: '※確認用',
                                                    oncopy: 'return false',
                                                    onpaste: 'return false',
                                                    oncontextmenu: 'return false',
                                                    class: 'form-control' %>

      <%= f.submit "アカウント登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <br>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>